image: jguyomard/hugo-builder:latest

before_script:
  - BUILD_DIR="/tmp/build"

  - eval `ssh-agent -s`
  - echo "$SSH_PRIVATE_KEY" | ssh-add /dev/stdin
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  script:
    - hugo --destination "$BUILD_DIR"
    - minify -r -o $BUILD_DIR/ $BUILD_DIR/
    - scp -P$SSH_PORT -r $BUILD_DIR/* root@$SSH_HOSTNAME:$DIRPATH