image: felicianotech/docker-hugo:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

stages:
  - build
  - deploy

cache:
  paths:
  - public


build:
  stage: build
  tags: neonxp
  script:
    - HUGO_ENV=production hugo

deploy:
  stage: deploy
  tags: neonxp
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - scp -P22 -r public/* root@185.143.172.56:/var/www/neonxp.net

