baseURL = "https://neonxp.ru"
title = "Уголок NeonXP"
copyright = "Александр NeonXP Кирюхин"

canonifyurls = true
languagecode = "ru"
theme = "whiteplain"

Paginate = 5

preserveTaxonomyNames = true

[params]
  sitename = "Бложик веб-разработчика"
  dateFormat = "02.01.2006"
[params.author]
  name = "Александр NeonXP Кирюхин"
  gravatar = "alexander@kiryukhin.su"
  email = "alexander@kiryukhin.su"

  twitter = "NeonXP"
  telegram = "NeonXP"

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Блог"
    title = "Блог"
    url = "/"
    weight = -110

  [[menu.gpg]]
    identifier = "gpg"
    name = "GPG ключи"
    title = "Мои GPG ключи"
    url = "/pages/gpg"
    weight = -100